### PR TITLE
Update print message

### PR DESCRIPTION
**Pull request by zxDiscovery**

### CODE REVIEW

**Comment by zxDiscovery** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **zxdiscovery**
You can assign the PR to them by writing `/assign @zxdiscovery` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=zxDiscovery%2Fhello).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/zxDiscovery/hello/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by zxDiscovery** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[vincent-pli](https://github.com/zxDiscovery/hello/pull/3#issuecomment-693131822 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=zxDiscovery%2Fhello).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/zxDiscovery/hello/blob/master/OWNERS)~~ [vincent-pli]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vincent-pli — CHANGES_REQUESTED** [review]
Change it, boy

**Comment by zxDiscovery** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **zxdiscovery**
You can assign the PR to them by writing `/assign @zxdiscovery` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=zxDiscovery%2Fhello).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/zxDiscovery/hello/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by zxDiscovery** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[vincent-pli](https://github.com/zxDiscovery/hello/pull/3#issuecomment-693132550 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=zxDiscovery%2Fhello).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/zxDiscovery/hello/blob/master/OWNERS)~~ [vincent-pli]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by zxDiscovery** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **zxdiscovery**
You can assign the PR to them by writing `/assign @zxdiscovery` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=zxDiscovery%2Fhello).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/zxDiscovery/hello/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by zxDiscovery** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[vincent-pli](https://github.com/zxDiscovery/hello/pull/3#issuecomment-693134382 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=zxDiscovery%2Fhello).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/zxDiscovery/hello/blob/master/OWNERS)~~ [vincent-pli]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
